services:
  redis:
    image: redis:7-alpine
    container_name: store-web-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
  minio:
    image: minio/minio
    container_name: store-web-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data          # dữ liệu sống sót cả khi xoá container
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      timeout: 3s
      retries: 5
volumes:
  redis-data:
  minio-data: